module.exports = {
  UPDATE_PLAYING_STATUS: 'UPDATE_PLAYING_STATUS',
  PLAY_NO_SUB: 'PLAY_NO_SUB',
  PLAY_SUB_PODCAST: 'PLAY_SUB_PODCAST',
  UPDATE_TIME_ELAPSED: 'UPDATE_TIME_ELAPSED',
  PLAY: 'PLAY',
  PAUSE: 'PAUSE'
}