module.exports = {
  SEARCH_RESULTS_RECEIVED: 'SEARCH_RESULTS_RECEIVED',
  PODCAST_LISTING_RECEIVED: 'PODCAST_LISTING_RECEIVED',
  STORE_DESCRIPTION: 'STORE_DESCRIPTION',
  LOAD_PODCAST: 'LOAD_PODCAST',
  RESET_SEARCH: 'RESET_SEARCH'
};
